const STORE='packy_reusable_v2';
const templates={
 pool:{name:'יום בבריכה',emoji:'🏖️',category:'משפחה',items:['בגדי ים','מגבות','בקבוקי מים','קרם הגנה','כובעים','מצופים','בגדי החלפה','חטיפים','שקית לבגדים רטובים','סנדלים','מגבונים','מפתחות וארנק']},
 morning:{name:'בוקר עם הילדים',emoji:'🌤️',category:'רוטינה',items:['צחצוח שיניים','להתלבש','גרביים ונעליים','חטיף בוקר','בקבוק מים','תיק לגן','שירותים לפני יציאה','יוצאים מהבית']},
 trip:{name:'לפני חופשה',emoji:'✈️',category:'נסיעות',items:['דרכונים','ביטוח נסיעות','מטענים','תרופות','לרוקן פח','לסגור חלונות','לכבות מכשירים','להשקות עציצים','להוריד מפות אופליין','לשלוח פרטי נסיעה למשפחה']},
 weekend:{name:'סופ״ש משפחתי',emoji:'🚗',category:'נסיעות',items:['בגדים לילדים','בגדים להורים','פיג׳מות','מברשות שיניים','מטענים','תרופות','בקבוקי מים','חטיפים לדרך','צעצוע אהוב','ספרים','מגבונים','נעליים נוספות']},
 gym:{name:'תיק לחדר כושר',emoji:'🏋️',category:'אישי',items:['נעלי ספורט','מגבת','בקבוק מים','אוזניות','שעון','חולצה להחלפה','מפתח ללוקר']},
 sitter:{name:'העברה לבייביסיטר',emoji:'🧸',category:'משפחה',items:['מה אוכלים בערב','שעת שינה','טלפונים לשעת חירום','ספר אהוב','תרופות אם צריך','מפתח לבית','Wi‑Fi','איפה הפיג׳מות','משהו חריג היום']}
};
let state=loadState();let activeListId=null;let studioFormat='checklist';let studioListId=null;
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORE)||'null');if(s&&Array.isArray(s.lists))return s}catch{}const lists=['pool','morning','weekend','gym','trip','sitter'].map((k,i)=>({id:uid(),...templates[k],items:templates[k].items.map(x=>({id:uid(),text:x,done:false,group:i%2?'רגיל':'חשוב'})),runs:[3,8,2,6,1,1][i],lastRun:null,created:Date.now()-i*86400000}));return{lists}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function current(){return state.lists.find(l=>l.id===activeListId)}
function totalRuns(){return state.lists.reduce((n,l)=>n+(l.runs||0),0)}
function renderAll(){renderHome();renderLibrary();renderTemplates();document.getElementById('statLists').textContent=state.lists.length;document.getElementById('statRuns').textContent=totalRuns()}
function renderHome(){const box=document.getElementById('homeCards');box.innerHTML=state.lists.slice(0,6).map(cardHtml).join('')}
function cardHtml(l){const total=l.items.length,done=l.items.filter(x=>x.done).length;return `<article class="list-card"><div class="list-icon">${l.emoji}</div><h3>${esc(l.name)}</h3><p>${total} פריטים · הורצה ${l.runs||0} פעמים</p><div class="list-meta"><span class="pill">${esc(l.category||'רשימה')}</span>${done?`<span class="pill">${done}/${total} מסומנים</span>`:''}</div><div class="card-actions"><button class="run-btn" onclick="runList('${l.id}')">Run</button><button class="design-btn" onclick="openStudio('${l.id}','checklist')">A4</button></div></article>`}
function renderLibrary(){document.getElementById('libraryRows').innerHTML=state.lists.map(l=>`<div class="library-row"><div class="emoji">${l.emoji}</div><div class="copy"><h3>${esc(l.name)}</h3><p>${l.items.length} פריטים · ${l.runs||0} הרצות · ${esc(l.category||'כללי')}</p></div><button onclick="runList('${l.id}')">הפעל</button></div>`).join('')}
function renderTemplates(){document.getElementById('templateCards').innerHTML=Object.entries(templates).map(([key,t])=>`<article class="list-card"><div class="list-icon">${t.emoji}</div><h3>${esc(t.name)}</h3><p>${t.items.length} פריטים מוכנים להתחלה</p><div class="list-meta"><span class="pill">${esc(t.category)}</span></div><div class="card-actions"><button class="run-btn" onclick="createFromTemplate('${key}')">השתמש בתבנית</button></div></article>`).join('')}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0)}
function go(where){document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(where==='home'){show('homeScreen');document.getElementById('navHome').classList.add('active')}if(where==='lists'){show('listsScreen');document.getElementById('navLists').classList.add('active')}if(where==='templates'){show('templatesScreen');document.getElementById('navTemplates').classList.add('active')}}
function openCreate(){document.getElementById('createModal').classList.add('show');setTimeout(()=>document.getElementById('createText').focus(),80)}
function closeCreate(){document.getElementById('createModal').classList.remove('show')}
function fillPrompt(t){document.getElementById('createText').value=t}
function quickGenerate(){const v=document.getElementById('quickPrompt').value.trim();document.getElementById('createText').value=v;generateFromPrompt()}
function detectTemplate(text){const t=text.toLowerCase();if(/מדבק|label|sticker/.test(t))return'labels';if(/בריכה|ים|pool|beach/.test(t))return'pool';if(/בוקר|גן|morning/.test(t))return'morning';if(/סופ|צימר|מלון|weekend/.test(t))return'weekend';if(/חופש|טיס|חו״ל|חול|vacation|flight/.test(t))return'trip';if(/כושר|gym/.test(t))return'gym';if(/בייבי|מטפל|sitter/.test(t))return'sitter';return'generic'}
function generateFromPrompt(){const text=document.getElementById('createText').value.trim();closeCreate();const type=detectTemplate(text);if(type==='labels'){const name=(text.match(/(?:השם|שם)\s+([^,\.]+)/)||[])[1]||'נועם';document.getElementById('studioTitle').value=name.trim();openStudio(null,'labels');return}let base=type==='generic'?null:templates[type];let items;if(base){items=base.items}else{items=text.split(/[\n,]+/).map(x=>x.trim()).filter(x=>x.length>1);if(items.length<4)items=['הדבר הכי חשוב','מים','מטען / סוללה','בגדים מתאימים','מה שצריך לילדים','משהו שאסור לשכוח'];}
const name=base?base.name:(text?text.slice(0,38):'רשימה חדשה');const l={id:uid(),name,emoji:base?.emoji||'✓',category:base?.category||'כללי',items:items.map((x,i)=>({id:uid(),text:x,done:false,group:i<3?'חשוב':'רגיל'})),runs:0,lastRun:null,created:Date.now()};state.lists.unshift(l);save();renderAll();toast('הרשימה נוצרה ונשמרה לפעם הבאה');setTimeout(()=>runList(l.id),350)}
function createFromTemplate(key){const t=templates[key];const l={id:uid(),name:t.name,emoji:t.emoji,category:t.category,items:t.items.map((x,i)=>({id:uid(),text:x,done:false,group:i<3?'חשוב':'רגיל'})),runs:0,lastRun:null,created:Date.now()};state.lists.unshift(l);save();renderAll();runList(l.id)}
function runList(id){activeListId=id;const l=current();if(!l)return;document.getElementById('runEmoji').textContent=l.emoji;document.getElementById('runTitle').textContent=l.name;renderRun();show('runScreen')}
function renderRun(){const l=current();if(!l)return;document.getElementById('runMeta').textContent=`${l.items.length} פריטים · ${l.runs||0} הרצות קודמות`;document.getElementById('runItems').innerHTML=l.items.map((x,i)=>`<div class="item ${x.done?'done':''}" onclick="toggleItem('${x.id}')"><div class="check">${x.done?'✓':''}</div><div class="item-text">${esc(x.text)}</div><span class="group-tag">${esc(x.group||'פריט')}</span></div>`).join('');const done=l.items.filter(x=>x.done).length;const p=l.items.length?Math.round(done/l.items.length*100):0;document.getElementById('runPercent').textContent=p+'%';document.getElementById('ring').style.background=`conic-gradient(var(--accent) 0 ${p}%,#eee8df ${p}% 100%)`}
function toggleItem(id){const l=current(),x=l?.items.find(i=>i.id===id);if(!x)return;x.done=!x.done;save();renderRun();renderAll()}
function addRunItem(){const inp=document.getElementById('addItemInput'),v=inp.value.trim();if(!v)return;const l=current();l.items.push({id:uid(),text:v,done:false,group:'נוסף עכשיו'});inp.value='';save();renderRun();renderAll();toast('נשמר גם לפעם הבאה')}
function resetRun(){const l=current();if(!l)return;l.items.forEach(x=>x.done=false);save();renderRun();renderAll();toast('הרשימה חזרה לנקודת ההתחלה')}
function finishRun(){const l=current();if(!l)return;l.runs=(l.runs||0)+1;l.lastRun=Date.now();l.items.forEach(x=>x.done=false);save();renderAll();toast('סיימנו. בפעם הבאה הכול יתחיל נקי');setTimeout(()=>go('home'),650)}
function openStudio(id,format='checklist'){studioListId=id||studioListId;const l=id?state.lists.find(x=>x.id===id):null;if(l){document.getElementById('studioTitle').value=l.name;document.getElementById('studioSubtitle').value='רשימה קבועה · מסמנים ומשתמשים שוב'}else if(format==='labels'&&!document.getElementById('studioTitle').value){document.getElementById('studioTitle').value='נועם'}setStudioFormat(format);renderPaper();show('studioScreen')}
function setStudioFormat(f){studioFormat=f;document.getElementById('segChecklist').classList.toggle('active',f==='checklist');document.getElementById('segLabels').classList.toggle('active',f==='labels');document.getElementById('labelCountLabel').style.display=f==='labels'?'block':'none';document.getElementById('labelCount').style.display=f==='labels'?'block':'none';document.getElementById('studioSubLabel').textContent=f==='labels'?'טקסט קטן (אופציונלי)':'שורת משנה';if(f==='labels'&&document.getElementById('studioTitle').value==='יום בבריכה')document.getElementById('studioTitle').value='נועם';renderPaper()}
function renderPaper(){const p=document.getElementById('paper');if(!p)return;const title=document.getElementById('studioTitle').value||'Packy';const sub=document.getElementById('studioSubtitle').value||'';const style=document.getElementById('studioStyle').value;p.className='paper '+style;if(studioFormat==='labels'){const q=Math.max(6,Math.min(30,Number(document.getElementById('labelCount').value)||18));const symbols=['★','☀','●','✦','♥','▲'];p.innerHTML=`<div class="paper-title">${esc(title)}</div><div class="paper-sub">${esc(sub||'מדבקות שם מוכנות להדפסה')}</div><div class="labels">${Array.from({length:q},(_,i)=>`<div class="label">${symbols[i%symbols.length]} ${esc(title)}<small>${esc(sub||'Packy')}</small></div>`).join('')}</div><div class="paper-footer"><span>A4 printable</span><span>Packy</span></div>`}else{const l=state.lists.find(x=>x.id===studioListId)||current()||state.lists[0];const items=(l?.items||[]).slice(0,14);p.innerHTML=`<div class="paper-title">${l?.emoji||'✓'} ${esc(title)}</div><div class="paper-sub">${esc(sub)}</div><div class="paper-list">${items.map(x=>`<div class="paper-item"><div class="paper-box"></div><span>${esc(x.text)}</span></div>`).join('')}</div><div class="paper-footer"><span>Never forget it twice.</span><span>Packy</span></div>`}}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2100)}
document.getElementById('createModal').addEventListener('click',e=>{if(e.target.id==='createModal')closeCreate()});document.getElementById('addItemInput').addEventListener('keydown',e=>{if(e.key==='Enter')addRunItem()});renderAll();renderPaper();